services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
      - .env.yml
    restart: always
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
