# This is a Docker Compose file for running a Kafka broker with controller functionality.
services:
  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "19092:19092"
      - "9093:9093"
      - "9092:9092"
    environment:
      # Listener setup
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9091,BROKER://0.0.0.0:19092,DOCKER://0.0.0.0:9093,HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://host.docker.internal:19092,DOCKER://kafka:9093,HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    volumes:
      - ./kafka-data:/var/lib/kafka/data
    
  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - 8090:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka